### PR TITLE
feat: add pydantic models for projects endpoint 

### PR DESCRIPTION
**Pull request by aliaksei-kuchyk**
# Motivation

As a user of this package I would like to use type checking for my payloads for projects endpoint to be sure I am sending valid requests before API actually returns error response.

# Solution

Added pydantic models and some tests

# TODO

- [x] Cover functionality with tests

### CODE REVIEW

**Review by bhodorog — APPROVED** [review]
lgtm

**Comment by pdeburen** [comment]
@aliaksei-kuchyk noticed that this is still not merged, anything left to do? do the guides need to be updated https://caplena.com/docs/sdk/python/creating-projects.html ?

**Comment by aliaksei-kuchyk** [comment]
Totally forgot about this one. Yes, documentation needs to be updated.

**Comment by pdeburen** [comment]
> Totally forgot about this one. Yes, documentation needs to be updated.

Ok, can you do this?

**Comment by aliaksei-kuchyk** [comment]
@pdeburen done, should I merge?

**Pull request merged**
